---
# Configuration file for Bitbucket Pipelines

# https://hub.docker.com/r/hseeberger/scala-sbt/
image: hseeberger/scala-sbt:11.0.10_1.4.7_2.13.5

pipelines:
  default:
    - step:
        name: Build
        caches:
          - sbt
        script:
          - sbt '++ 3.0.0' scalaVersion sbtVersion version clean compile test package assembly
          - sbt '++ 2.13.6' scalaVersion sbtVersion version clean compile test package assembly
          - sbt '++ 2.12.14' scalaVersion sbtVersion version clean compile test package assembly
          - sbt '++ 2.11.12' scalaVersion sbtVersion version clean compile test package assembly


