/*
 * This file is automatically generated. Do not edit.
 */

package soda.lib

/**
 * This is a constant to be used in enumerations.
 */
trait EnumConstant {

  def ordinal: Int

  def name: String

  override
  lazy val toString: String = "" + ordinal + "-" + name
}
