/*
 * This file is automatically generated. Do not edit.
 */

package soda.lib

/**
 * This is a Seq implemented without exceptions.
 */
trait SeqSD [T] {

  def opt [B]  (ifEmpty: B, ifNonEmpty: NonEmptySeqSD [T] => B ): B

  def toSeq: Seq [T]

  def reverse: SeqSD [T]

  override
  lazy val toString: String = toSeq.toString
}

trait EmptySeqSD [T] extends SeqSD [T] {

  def opt [B]  (ifEmpty: B, ifNonEmpty: NonEmptySeqSD [T] => B ): B = ifEmpty

  lazy val toSeq: Seq [T] = Seq [T]  ()

  lazy val reverse: EmptySeqSD [T] = this
}

case class _EmptySeqSD [T]  () extends EmptySeqSD [T]

trait NonEmptySeqSD [T] extends SeqSD [T] {

  def opt [B]  (ifEmpty: B, ifNonEmpty: NonEmptySeqSD [T] => B ): B = ifNonEmpty (this )

  lazy val head: T = toSeq.head

  lazy val tail: SeqSD [T] = SeqSDBuilderImpl [T]  () .build (toSeq.tail )

  lazy val reverse: NonEmptySeqSD [T] = _NonEmptySeqSD (toSeq.reverse )
}

case class _NonEmptySeqSD [T]  (toSeq: Seq [T]  ) extends NonEmptySeqSD [T]

trait SeqSDBuilder [T] {

  def build (seq: Seq [T]  ): SeqSD [T] =
    if (seq.isEmpty
    ) _EmptySeqSD [T]  ()
    else _NonEmptySeqSD [T]  (seq )
}

case class SeqSDBuilderImpl [T]  () extends SeqSDBuilder [T]
