---
# CI configuration
# https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven
# https://github.com/actions/setup-java

name: Scala CI

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - 11.0.21
        - 17.0.9
        - 21.0.1
        scala:
        - 2.11.12
        - 2.12.18
        - 2.13.12
        - 3.3.1
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - name: Build with sbt
      run: sbt '++ ${{ matrix.scala }}' scalaVersion sbtVersion version clean compile test package assembly


